services:
  provisioner:
    build: ./mail-provisioner
    container_name: mail-provisioner
    ports:
      - "8000:8000"
    volumes:
      - ./tenants:/app/tenants
      - ./templates:/app/templates
    env_file:
      - .env
    restart: unless-stopped
